### ISSUE TITLE
Lack of global information in interaction experiment

### ISSUE THREAD

**Issue by Dekai21** [roggirg/AutoBots#10]
Hi,

I just noticed that the global information is removed in the interaction dataset experiment at: https://github.com/roggirg/AutoBots/blob/3a61ad9f80603f99ab1e9cc535acccf72c5d6bea/datasets/interaction_dataset/dataset.py#L343. After doing this, the agents couldn't get the actual social information of other agents, because the remaining data is just from the individual local perspective. Have you found out the reason why the performance of the model is even worse after adding the global position? :)

**Comment by roggirg** [comment]
Hi,

No sadly I have not explored that part in detail. But it would be interesting to know if you gather any insight.
