### ISSUE TITLE
create_h5_nusc.py

### ISSUE THREAD

**Issue by cjmdd** [roggirg/AutoBots#11]
when I run python create_h5_nusc.py ****, there are some errors as follows

return self.data.get('sample_annotation', self.inst_sample_to_ann[(sample_token, instance_token)])
KeyError: ('faf2ea71b30941329a3c3f3866cec714', '4d87aaf2d82549969f1550607ef46a63')

**Comment by roggirg** [comment]
Hi @cjmdd 

Sorry for the delayed response. I'm not sure why you are getting this error, and if you are still getting it. It could be an api version update. Can you send me some details on the nuscenes version you are running.

Thanks

**Comment by KYYOnull** [comment]
i have the same question.. how did you resolve it?  ithink it's not api version cause
