### ISSUE TITLE
How do you handle incomplete trajectories for the test dataset?

### ISSUE THREAD

**Issue by FUTUREEEEEE** [roggirg/AutoBots#12]
Hi @roggirg:
Thank you for your amazing work! I have a question about how you handle incomplete trajectories in INTERACTION dataset. I notice that you ignore all the trajectories that are incomplete (Less than 40 frames), [https://github.com/roggirg/AutoBots/blob/3a61ad9f80603f99ab1e9cc535acccf72c5d6bea/datasets/interaction_dataset/create_h5_indst.py#L52](url) do you also do this at the submission stage?  

Looking forward to your reply.

**Comment by roggirg** [comment]
Hello,
At the submission stage, as stated [here](https://github.com/interaction-dataset/INTERPRET_challenge_multi-agent) only agents with track_to_predict=1 are used at eval. The rows with track_to_predict=1 are ones that have a complete history (i.e., have 10 input timesteps).

**Comment by FUTUREEEEEE** [comment]
Thank you for your quick response and explanation. I understand your point and it makes sense. I appreciate your help with this issue.
