### ISSUE TITLE
The choice of "ego_idx" in INTERACTION dataset 

### ISSUE THREAD

**Issue by FUTUREEEEEE** [roggirg/AutoBots#13]
Hi @roggirg:
I have a question about the role of `ego_idx `in the INTERACTION dataset, I noticed that you generate an `ego_idx `from random sampling in [https://github.com/roggirg/AutoBots/blob/3a61ad9f80603f99ab1e9cc535acccf72c5d6bea/datasets/interaction_dataset/dataset.py#L164](url).
Why is an `ego_idx `necessary? Is `ego_idx `  only used as a coordinate origin? 
Will the different choices of `ego_idx ` affect the performance of a model in the same case (i.e. the same sample)?

Thanks a lot! Looking forward to your reply.

**Comment by roggirg** [comment]
Hi @FUTUREEEEEE ,

Sorry for the delayed response. The choice of `ego_idx` is arbitrary and should not affect the results. We only do this so that it can be compatible with other datasets for "code cleanliness".

Thanks
