### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by krishnakanthnakka** [roggirg/AutoBots#14]
Dear Authors,

Would you mind releasing the pre-trained models on the trajnet++ dataset?

Thanks

**Comment by roggirg** [comment]
Hi @krishnakanthnakka ,

Unfortunately, we don't have any pre-trained models on the synthetic partition of the trajnet++ dataset. But I don't think it would be too difficult to train an Autobot-Joint model on it (~1hr on a GPU). If you're having trouble doing this, let me know and I'll see what I can do.

Thanks,
