### ISSUE TITLE
How to get the result without map 

### ISSUE THREAD

**Issue by liuyueChang** [roggirg/AutoBots#18]
![image](https://github.com/roggirg/AutoBots/assets/112742491/95bc2ec5-103a-4932-988b-f683333346af)
Thank you for your excellent work!
I have a simple question, if I want to train the model without map infomation. 
What I should do is just to change the option `--use-map-lanes` from True to False?

Thank you very much!

**Comment by Dhagash4** [comment]
Yeah that will work. If you want more detail please look at the `__getitem__` function of the respective dataset https://github.com/roggirg/AutoBots/blob/3a61ad9f80603f99ab1e9cc535acccf72c5d6bea/datasets/argoverse/dataset.py#L40CL44
