### ISSUE TITLE
Do all agents in a scene share the same mode classification probability?

### ISSUE THREAD

**Issue by ultimatedigiman** [roggirg/AutoBots#2]
First of all, thanks for sharing the work to the community!

1. The dimentions of  `mode_probs` returned by autobot joint inference is `(batch_size,num_mode)` which does not contain the number of agents in the scene(`M`)

https://github.com/roggirg/AutoBots/blob/d492be7e47f23be9941cf9aa420c9d77ec8fdb60/train.py#L301
This means **all the agents sharing the same** mode classification probability and mode ordering, is that reasonable?

2. Small oversight in the nuScenes joint training command line arguments in `README.md`:
```--use-map-image True``` should be changed to ```--use-map-lanes True```

**Comment by roggirg** [comment]
Thank you for your interest!

1. Yes that is correct. In the joint version, the modes are across the entire scene.
2. Nice catch, thank you!

**Comment by ultimatedigiman** [comment]
But why all agents in a scene can share the same modes?
Considering they may have different directions,velocities etc.

**Comment by roggirg** [comment]
The mode here is across the entire scene, so there could be certain scene modes with some agents that turn right and some that turn left. Basically, AutoBot-Joint generates c possible future *scenes*, and maximum likelihood ensures that each agent's most likely maneuver (mode) coincides with the other agents, at least in theory. This is why AutoBot-Joint performs well under joint metrics.

**Comment by ultimatedigiman** [comment]
Thanks for the explanation, I mistook _scene modes_ for  _agent modes_, just like the AutoBot-Ego version.
