### ISSUE TITLE
Question about negative loss

### ISSUE THREAD

**Issue by CHEN-H01** [roggirg/AutoBots#7]
Hi, I am very interested in your work! There's a question that baffles me:

I found that the nll loss is a negative number when training autobots, I wonder if this is a normal phenomenon? Why is nll loss a negative number?

**Comment by roggirg** [comment]
Hi, Thank you for your interest in our work.

Indeed, this is normal behavior. NLL can have negative values when parameterizing Gaussian distributions.

Thanks!

**Comment by CHEN-H01** [comment]
Ohh, thanks! Because I've never seen negative loss can be used to train a model.
