### ISSUE TITLE
question about “AutoBot-Ego (ensemble)”

### ISSUE THREAD

**Issue by CHEN-H01** [roggirg/AutoBots#9]
Hi, I wonder what does it mean here? Or how did you do it (where I highlight) ? Thanks! 
![93fb60937015a866f027842109e913a](https://user-images.githubusercontent.com/73165749/190303935-08126714-2a74-46ca-96b5-a2f18fd098db.jpg)

**Comment by roggirg** [comment]
Hi,

Unfortunately, I have not yet had a chance to include this function from my private repo. 
But the idea is quite simple: after having trained multiple models, you can combine their predictions for a specific scene by averaging out predictions that are close to each other. That is, find the closest modes (using e.g., euclidean distance) and average their predictions per timestep.

I'll try to get to it in a few weeks. Let me know if you have any questions.

**Comment by CHEN-H01** [comment]
Oh I know what you mean! It is a simple yet effective method haha! Looking forward to your code, and I will try to implement it also.
